Repository parrt/tensor-sensor, pull requests merged in 2021-09, with the labels that each got.

#26 Use latex times for > 3d tensors
  tsensor/viz.py
Labels: enhancement

#27 feat: explainer support pdf
  tsensor/analysis.py
Labels: enhancement

#29 fix: full path
  tsensor/analysis.py
Labels: bug

#30 General clean up
  README.md
  setup.py
  testing/viz_testing.py
  tsensor/__init__.py
  tsensor/analysis.py
  tsensor/viz.py
Labels: enhancement

#36 fix: specific mono fallback font
  tsensor/analysis.py
Labels: bug, enhancement
